planta(digitaria).
planta(opio).
planta(ipeca).
planta(nuez_vomica).
planta(eleboro_blanco).
planta(colchico).
planta(belladona).
planta(quina).
planta(cacao).
planta(retama).
planta(coca).
planta(peyote).
planta(efedra).
planta(barrasco).
planta(nenufar_amarillo).
planta(artemisa).
planta(semilla_de_yute).
planta(toloache).
planta(eucalipto).
planta(rosal).
palabra(afrodisiaca).
palabra(analgesica).
palabra(anestesica).
palabra(antidiarreica).
palabra(antiespasmodica).
palabra(antiflogistica).
palabra(antipiretica).
palabra(antiseptica).
palabra(aperitiva).
palabra(astringente).
palabra(carminativa).
palabra(colagoga).
palabra(depurativa).
palabra(diaforetica).
palabra(digestiva).
palabra(diuretica).
palabra(emetica).
palabra(emenagoga).
palabra(estupefaciente).
palabra(hemostatica).
palabra(hepatica).
palabra(laxante).
palabra(pectoral).
palabra(sedante).
palabra(tonica).
palabra(toxica).
palabra(vermifuga).
palabra(vulneraria).
planta().
planta(abrojo).
planta(acacia).
planta(acanto).
planta(aceitilla).
planta(achicoria).
planta(malva).
planta(zarzaparrilla).
planta(anís).
planta(perejil).
planta(sanguinaria).
planta(limon).
planta(sauco).
planta(árnica).
planta(llanten).
planta(fenogreco).
planta(zarzamora).
planta(salvia).
planta(tilo).
planta(valeriana).
planta(yerbabuena).
planta(manzanilla).
planta(jugo_de_limón).
planta(jugo_de_toronja).
planta(pingüica).
planta(quinoa_roja).
planta(encino_rojo).
planta(pimiento).
planta(salvia).
planta(huramelis).
planta(sanguinaria).
planta(cola_de_caballo).
planta(arnica).
planta(sauco).
planta(ajenjo_).
planta(germen_de_trigo).
planta(quira).
planta(canela).
planta(alholva).
planta(eucalipto).
planta(cebada).
planta(salvia).
planta(tabachin).
planta(borraja).
planta(ajenjo_).
planta(gerciana).
planta(yerbabuena).
planta(limón).
planta(genciana_).
planta(cardo).
planta(zarzaparrilla).
planta(arnica).
planta(chicalote).
planta(alcanfor).
planta(toronja).
planta(limón).
planta(genciana_).
planta(cardo).
planta(zarzaparrilla).
planta(arnica).
planta(chicalote).
planta(alcanfor).
planta(toronja).
planta(eucalipto).
planta(merrubio).
planta(toloache).
planta(oregano).
planta(salvia).
planta(lupulo).
planta(eucalipto).
planta(cuasia).
planta(uva_).
planta(cerezo).
planta(malva).
planta(rosal).
planta(limón).
planta(salvia).
planta(rosal).
planta(encina).
planta(salvia).
planta(zarzamora).
planta(eucalipto).
planta(borraga).
planta(anacahuite).
planta(gordolobo).
planta(tilo).
planta(benjui).
planta(marrubio).
planta(rabano).
planta(gordolobo).
planta(eucalipto).
planta(ipecacuana).
planta(mostaza).
planta(ortiga).
planta(espinosilla).
planta(marrubio).
planta(romero).
planta(anís).
planta(tila).
planta(manzanilla).
planta(ajenjo_).
planta(diente_de_león).
planta(aceite_de_oliva).
planta(retama).
planta(cabellos_de_elote).
planta(pinguica_).
planta(cola_de_caballo).
planta(ajo).
planta(cebolla).
planta(hiedra).
planta(cola_de_caballo).
planta(ortiga).
planta(limón).
planta(romero).
planta(cuachalalate).
planta(llanten).
planta(siempreviva).
planta(mastuerzo).
planta(higuera).
planta(sauco).
planta(toronjil).
planta(sanguinaria).
planta(salvia).
planta(hamamelis).
planta(cola_de_caballo).
planta(doradilla).
planta(ajo).
planta(cabellos_de_elote).
planta(menta).
planta(hinojo).
planta(manzanilla).
planta(toronjil).
planta(boldo).
planta(linaza).
planta(anís).
planta(romero).
planta(cola_de_caballo).
planta(árnica_).
planta(hamamelis).
planta(laurel).
planta(briania).
planta(digital).
planta(salvia).
planta(nuez_de_kcla).
planta(tejocote).
planta(achicoria).
planta(diente_de_león).
planta(apio).
planta(sanguinaria).
planta(zarzaparrilla).
planta(berro).
planta(matarique).
planta(tronadora).
planta(bucalipto).
planta(damiana).
planta(capulín).
planta(mezquite).
planta(tlalchichinole).
planta(linaza).
planta(membrillo).
planta(arroz).
planta(cebada).
planta(guayaba).
planta(albahaca).
planta(granada).
planta(manzanilla).
planta(sinionillo).
planta(siempreviva).
planta(chaparro_amargoso).
planta(muicle).
planta(monacillo).
planta(limón).
planta(naranja).
planta(tamarindo).
planta(chaparro_amargoso).
planta(ipecacuana).
planta(cedrón).
planta(anís).
planta(menta).
planta(yerbabuena).
planta(diente_de_león).
planta(té_de_limón).
planta(quina).
planta(genciana_).
planta(tabequillo).
planta(ruibaxbo).
planta(anís_estrella).
planta(valeriana).
planta(manzanilla).
planta(alcanfor).
planta(tamarindo).
planta(linaza).
planta(cedrón).
planta(llanten).
planta(valeriana).
planta(hierba_del_pollo).
planta(cebolla).
planta(perejil).
planta(sauco).
planta(hiedra).
planta(zanahoria).
planta(borraja).
planta(sauco).
planta(cebolla).
planta(ajo).
planta(limón).
planta(berro).
planta(cebolla).
planta(geranio).
planta(ciruela).
planta(linaza).
planta(chía).
planta(tamarindo).
planta(agar-agar).
planta(eucalipto).
planta(lavanda).
planta(anacahuite).
planta(apio).
planta(tomillo).
planta(perejil).
planta(anís).
planta(hinojo).
planta(toronjil).
planta(romero).
planta(ruibarbo).
planta(ruda).
planta(menta).
planta(ármica).
planta(alfalfa_).
planta(lino).
planta(malvavisco).
planta(romero).
planta(quina).
planta(genciana_).
planta(orégano).
planta(fenogreco).
planta(malvavisco).
planta(hiedra).
planta(manzanilla).
planta(anís_de_estrella).
planta(cola_de_caballo).
planta(doradilla).
planta(zarzaparrilla).
planta(apio).
planta(cerezo).
planta(limón).
planta(pino).
planta(alcanfor).
planta(aconito).
planta(belladona).
planta(beleño).
planta(colchico).
planta(chicalote).
planta(encina).
planta(encina).
planta(nogal).
planta(milenrana).
planta(eucalipto).
planta(limón).
planta(quina).
planta(zarzaparrilla).
planta(calendula).
planta(hinojo).
planta(menta).
planta(mastuerzo).
planta(ortiga).
planta(rosal).
planta(retama).
planta(boldo).
planta(alcachofa).
planta(prodigiosa).
planta(cáscara_sagrada).
planta(helecho).
planta(ricino).
planta(tabaco).
planta(linaza).
planta(llanten).
planta(árnica_).
planta(hamamelis).
planta(alcachofa).
planta(cardo).
planta(perejil).
planta(sauco).
planta(berros).
planta(retama).
planta(marrubio).
planta(boldo).
planta(doradilla).
planta(ruibarbo).
planta(manzanilla).
planta(lechuga).
planta(tila).
planta(papoloquelite).
planta(achicoria).
planta(berros).
planta(llanten).
planta(retama).
planta(tecomasuchil).
planta(ajo).
planta(esparrago).
planta(alpiste).
planta(muerdago).
planta(miel).
planta(nuez_de_kola).
planta(crategus).
planta(acedera).
planta(anís).
planta(hinojo).
planta(tila).
planta(valeriana).
planta(azahar).
planta(beleño).
planta(gelsenio).
planta(tila).
planta(valeriana).
planta(pastiflora).
planta(azahar).
planta(menta).
planta(manzanilla).
planta(lechuga).
planta(genciana_).
planta(melisa).
planta(yohimbo).
planta(damiana).
planta(nuex_vómica).
planta(aguacate).
planta(manzanilla).
planta(acónito).
planta(valeriana).
planta(tila).
planta(chicalote).
planta(hinojo).
planta(anís).
planta(menta).
planta(perejil).
planta(zanahoria).
planta(acónito).
planta(borraja).
planta(cebolla).
planta(rosal).
planta(benjui).
planta(encina).
planta(encina).
planta(zarzaparrilla).
planta(pino).
planta(enebro).
planta(genciana_).
planta(ajenjo).
planta(ajo).
planta(cebolla).
planta(brionia).
planta(aguacate).
planta(papaya).
planta(avena).
planta(cebada).
planta(tomillo).
planta(verbena).
planta(fenogreco).
planta(eucalipto).
planta(llanten).
planta(sanguinaria).
planta(quina).
planta(girasol).
planta(eucalipto).
planta(cardo).
planta(azahar).
planta(hamamelis).
planta(tila).
planta(quina_roja).
planta(azafrán).
planta(hamamelis).
planta(belladona).
planta(anís_de_estrella).
planta(ruda).
planta(ajenjo).
planta(manzanilla).
planta(apio).
planta(hisopol).
planta(quina_amarilla).
planta(sabina).
planta(artemisa).
planta(hamamelis).
planta(zoapatle).
planta(perejil).
planta(cuercillo).
planta(clavo).
planta(heidra).
planta(ortiga).
planta(cola_de_caballo).
planta(ruda).
planta(eucalipto).
planta(anís).
planta(ajenjo).
planta(menta).
planta(salvia).
planta(manzanilla).
planta(menta).
planta(valeriana).
planta(bolde).
planta(rasiflora).
planta(té_negro).
planta(mate).
planta(valeriana).
planta(linaza).
planta(grama).
planta(cebada).
planta(llanten).
planta(doradilla).
planta(espárrago_ruda).
planta(toronjil).
planta(marrubio).
planta(limón).
planta(malva).
planta(esparrago).
planta(boldo).
planta(aceite_de_oliva).
planta(llanten).
planta(hiedra).
planta(manzanilla).
planta(limón).
planta(llanten).
planta(salvia).
planta(ruda).
planta(rosal).
planta(ajenjo).
planta(quina).
planta(berros).
planta(genciana_).
planta(rabano).
planta(papaija).
planta(laurel).
planta(encina).
planta(miel).
planta(perejil).
planta(cebolla).
planta(puerro).
planta(fresno).
planta(ipecacuana).
planta(alcanfor).
planta(perejil).
planta(hamamelis).
planta(anagálida).
planta(jengibre).
planta(linaza).
planta(cardo).
planta(girasol).
planta(ipecacuana).
planta(cola_de_caballo).
planta(eucalipto).
planta(ocote).
planta(gordolobo).
planta(borraja).
planta(sauco).
planta(linaza).
planta(cebolla).
planta(hiedra).
planta(gordolobo).
planta(nogal).
planta(ajo).
planta(apio).
planta(borraja).
planta(gobernadora).
planta(pino).
planta(romero).
planta(sanguinaria).
planta(marrubio).
planta(tabaco).
planta(cabellos_de_elote).
planta(cola_de_caballo).
planta(apio).
planta(eucalipto).
planta(pino).
planta(gordolobo).
planta(ajo).
planta(cebolla).
planta(estafiate).
planta(valeriana).
planta(borraja).
planta(ortiga).
planta(sauco).
planta(ajo).
planta(alcanfor).
planta(menta).
planta(tomillo).
planta(romero).
planta(encina).
planta(salvia).
planta(tila).
planta(limón).
planta(tamarindo).
planta(pirúl).
planta(semilla_de_calabaza).
planta(coquito_de_aceite).
planta(helecho_macho).
planta(encina).
planta(alcanfor).
planta(borraja).
planta(quina_).
planta(canela).
planta(romero).
planta(salvia).
planta(berro_).
planta(tamarindo).
planta(salvia).
planta(eucalipto).
planta(capulín).
planta(cedrón).
planta(salvia).
planta(malva).
planta(marrubio).
planta(gelsemio).
planta(quina).
planta(rábano).
planta(violeta).
planta(jugo_de_vástago_de_plá).
planta(mastuerzo).
planta(berro).
planta(ajo).
planta(eucalipto).
planta(pirúl).
planta(pino).
planta(roble).
planta(cuachalalate).
planta(sanguinaria).
planta(cola_de_caballo).
planta(girasol).
planta(limón).
planta(ruibarbo).
planta(hamamelis).
planta(castaño_de_indias).
planta(llanten).
planta(toronjil).
planta(apio).
planta(cipres).
planta(cola_de_caballo).
planta(ortiga).
planta(malva).
planta(leche_de_higuera).
planta(cebolla).
planta(nogal).
planta(albahaca).
planta(espino).
planta(menta).
planta(tila).
planta(marrubio).
planta(valeriana).
planta(salvia).
planta(cilantro).
planta(ajo).
planta(limón).
planta(pino).
planta(alfalfa).
planta(espinacas).
planta(acelga).
planta(berro).
planta(cebolla).
planta(limón).
planta(zanahoria).
planta(malva).
planta(zarzaparrilla).
planta(anís).
planta(perejil).
planta(sanguinaria).
planta(limon).
planta(sauco).
planta(árnica).
planta(llanten).
planta(fenogreco).
planta(zarzamora).
planta(salvia).
planta(tilo).
planta(valeriana).
planta(yerbabuena).
planta(manzanilla).
planta(jugo_de_limón).
planta(jugo_de_toronja).
planta(pingüica).
planta(quinoa_roja).
planta(encino_rojo).
planta(pimiento).
planta(salvia).
planta(huramelis).
planta(sanguinaria).
planta(cola_de_caballo).
planta(arnica).
planta(sauco).
planta(ajenjo).
planta(germen_de_trigo).
planta(quira).
planta(canela).
planta(alholva).
planta(eucalipto).
planta(cebada).
planta(salvia).
planta(tabachin).
planta(borraja).
planta(ajenjo).
planta(gerciana).
planta(yerbabuena).
planta(limón).
planta(genciana).
planta(cardo).
planta(zarzaparrilla).
planta(arnica).
planta(chicalote).
planta(alcanfor).
planta(toronja).
planta(limón).
planta(genciana).
planta(cardo).
planta(zarzaparrilla).
planta(arnica).
planta(chicalote).
planta(alcanfor).
planta(toronja).
planta(eucalipto).
planta(merrubio).
planta(toloache).
planta(oregano).
planta(salvia).
planta(lupulo).
planta(eucalipto).
planta(cuasia).
planta(uva).
planta(cerezo).
planta(malva).
planta(rosal).
planta(limón).
planta(salvia).
planta(rosal).
planta(encina).
planta(salvia).
planta(zarzamora).
planta(eucalipto).
planta(borraga).
planta(anacahuite).
planta(gordolobo).
planta(tilo).
planta(benjui).
planta(marrubio).
planta(rabano).
planta(gordolobo).
planta(eucalipto).
planta(ipecacuana).
planta(mostaza).
planta(ortiga).
planta(espinosilla).
planta(marrubio).
planta(romero).
planta(anís).
planta(tila).
planta(manzanilla).
planta(ajenjo).
planta(diente_de_león).
planta(aceite_de_oliva).
planta(retama).
planta(cabellos_de_elote).
planta(pinguica).
planta(cola_de_caballo).
planta(ajo).
planta(cebolla).
planta(hiedra).
planta(cola_de_caballo).
planta(ortiga).
planta(limón).
planta(romero).
planta(cuachalalate).
planta(llanten).
planta(siempreviva).
planta(mastuerzo).
planta(higuera).
planta(sauco).
planta(toronjil).
planta(sanguinaria).
planta(salvia).
planta(hamamelis).
planta(cola_de_caballo).
planta(doradilla).
planta(ajo).
planta(cabellos_de_elote).
planta(menta).
planta(hinojo).
planta(manzanilla).
planta(toronjil).
planta(boldo).
planta(linaza).
planta(anís).
planta(romero).
planta(cola_de_caballo).
planta(árnica).
planta(hamamelis).
planta(laurel).
planta(briania).
planta(digital).
planta(salvia).
planta(nuez_de_kcla).
planta(tejocote).
planta(achicoria).
planta(diente_de_león).
planta(apio).
planta(sanguinaria).
planta(zarzaparrilla).
planta(berro).
planta(matarique).
planta(tronadora).
planta(bucalipto).
planta(damiana).
planta(capulín).
planta(mezquite).
planta(tlalchichinole).
planta(linaza).
planta(membrillo).
planta(arroz).
planta(cebada).
planta(guayaba).
planta(albahaca).
planta(granada).
planta(manzanilla).
planta(sinionillo).
planta(siempreviva).
planta(chaparro_amargoso).
planta(muicle).
planta(monacillo).
planta(limón).
planta(naranja).
planta(tamarindo).
planta(chaparro_amargoso).
planta(ipecacuana).
planta(cedrón).
planta(anís).
planta(menta).
planta(yerbabuena).
planta(diente_de_león).
planta(té_de_limón).
planta(quina).
planta(genciana).
planta(tabequillo).
planta(ruibaxbo).
planta(anís_estrella).
planta(valeriana).
planta(manzanilla).
planta(alcanfor).
planta(tamarindo).
planta(linaza).
planta(cedrón).
planta(llanten).
planta(valeriana).
planta(hierba_del_pollo).
planta(cebolla).
planta(perejil).
planta(sauco).
planta(hiedra).
planta(zanahoria).
planta(borraja).
planta(sauco).
planta(cebolla).
planta(ajo).
planta(limón).
planta(berro).
planta(cebolla).
planta(geranio).
planta(ciruela).
planta(linaza).
planta(chía).
planta(tamarindo).
planta(agar_agar).
planta(eucalipto).
planta(lavanda).
planta(anacahuite).
planta(apio).
planta(tomillo).
planta(digitaria).
planta(opio).
planta(ipeca).
planta(nuez_vómica).
planta(eleboro_blanco).
planta(colchico).
planta(belladona).
planta(quina).
planta(cacao).
planta(retama).
planta(coca).
planta(peyote).
planta(efedra).
planta(barrasco).
planta(nenufar_amarillo).
planta(artemisa).
planta(semilla_de_yute).
planta(toloache).
planta(eucalipto).
planta(rosal).
%Caracteristicas
caracteristica(afrodisiaca).
caracteristica(analgesica).
caracteristica(anestesica).
caracteristica(antidiarreica).
caracteristica(antiespasmodica).
caracteristica(antiflogistica).
caracteristica(antipiretica).
caracteristica(antiseptica).
caracteristica(aperitiva).
caracteristica(astringente).
caracteristica(carminativa).
caracteristica(colagoga).
caracteristica(depurativa).
caracteristica(diaforetica).
caracteristica(digestiva).
caracteristica(diuretica).
caracteristica(emetica).
caracteristica(emenagoga).
caracteristica(estupefaciente).
caracteristica(hemostatica).
caracteristica(hepatica).
caracteristica(laxante).
caracteristica(pectoral).
caracteristica(sedante).
caracteristica(tonica).
caracteristica(toxica).
caracteristica(vermifuga).
caracteristica(vulneraria).
%padecimientos
padecimiento(anemia).
padecimiento(debilidad).
padecimiento(gripe).
padecimiento(gases).
padecimiento(mala_digestion).
padecimiento(colicos).
padecimiento(nauseas).
padecimiento(flatulencias).
padecimiento(mala_digestion).
padecimiento(nubes_en_los_ojos).
padecimiento(abscesos).
padecimiento(absceso_hepático).
padecimiento(acidez_estomacal).
padecimiento(acidez_estomacal).
padecimiento(ácido_úrico).
padecimiento(ácido_úrico).
padecimiento(ácido_úrico).
padecimiento(acné).
padecimiento(aftas).
padecimiento(aftas).
padecimiento(aftas).
padecimiento(agotamiento).
padecimiento(agotamiento).
padecimiento(agotamiento).
padecimiento(agruras).
padecimiento(agruras).
padecimiento(agruras).
padecimiento(agruras).
padecimiento(albuminaria).
padecimiento(albuminaria).
padecimiento(albuminaria).
padecimiento(alcoholismo).
padecimiento(almorranas).
padecimiento(almorranas).
padecimiento(almorranas).
padecimiento(almorranas).
padecimiento(almorranas).
padecimiento(almorranas).
padecimiento(anemia).
padecimiento(anemia).
padecimiento(anemia).
padecimiento(anemia).
padecimiento(anemia).
padecimiento(anginas).
padecimiento(anginas).
padecimiento(anginas).
padecimiento(anginas).
padecimiento(anginas).
padecimiento(anorexia).
padecimiento(anorexia).
padecimiento(anorexia).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(asma).
padecimiento(asma).
padecimiento(asma).
padecimiento(asma).
padecimiento(asma).
padecimiento(atonia_estomacal).
padecimiento(atonia_estomacal).
padecimiento(atonia_estomacal).
padecimiento(bazo).
padecimiento(bazo).
padecimiento(inflamación_de_la_boca).
padecimiento(inflamación_de_la_boca).
padecimiento(inflamación_de_la_boca).
padecimiento(inflamación_de_la_boca).
padecimiento(estomatitis).
padecimiento(estomatitis).
padecimiento(estomatitis).
padecimiento(estomatitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronconeumonia).
padecimiento(bronconeumonia).
padecimiento(bronconeumonia).
padecimiento(bronconeumonia).
padecimiento(caida_del_cabello).
padecimiento(caida_del_cabello).
padecimiento(caida_del_cabello).
padecimiento(caida_del_cabello).
padecimiento(calambres).
padecimiento(abscesos).
padecimiento(absceso_hepático).
padecimiento(acidez_estomacal).
padecimiento(acidez_estomacal).
padecimiento(ácido_úrico).
padecimiento(ácido_úrico).
padecimiento(ácido_úrico).
padecimiento(acné).
padecimiento(aftas).
padecimiento(aftas).
padecimiento(aftas).
padecimiento(agotamiento).
padecimiento(agotamiento).
padecimiento(agotamiento).
padecimiento(agruras).
padecimiento(agruras).
padecimiento(agruras).
padecimiento(agruras).
padecimiento(albuminaria).
padecimiento(albuminaria).
padecimiento(albuminaria).
padecimiento(alcoholismo).
padecimiento(almorranas).
padecimiento(almorranas).
padecimiento(almorranas).
padecimiento(almorranas).
padecimiento(almorranas).
padecimiento(almorranas).
padecimiento(anemia).
padecimiento(anemia).
padecimiento(anemia).
padecimiento(anemia).
padecimiento(anemia).
padecimiento(anginas).
padecimiento(anginas).
padecimiento(anginas).
padecimiento(anginas).
padecimiento(anginas).
padecimiento(anorexia).
padecimiento(anorexia).
padecimiento(anorexia).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(arterosclerosis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(artritis).
padecimiento(asma).
padecimiento(asma).
padecimiento(asma).
padecimiento(asma).
padecimiento(asma).
padecimiento(atonia_estomacal).
padecimiento(atonia_estomacal).
padecimiento(atonia_estomacal).
padecimiento(bazo).
padecimiento(bazo).
padecimiento(inflamación_de_la_boca).
padecimiento(inflamación_de_la_boca).
padecimiento(inflamación_de_la_boca).
padecimiento(inflamación_de_la_boca).
padecimiento(estomatitis).
padecimiento(estomatitis).
padecimiento(estomatitis).
padecimiento(estomatitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronquitis).
padecimiento(bronconeumonia).
padecimiento(bronconeumonia).
padecimiento(bronconeumonia).
padecimiento(bronconeumonia).
padecimiento(caida_del_cabello).
padecimiento(caida_del_cabello).
padecimiento(caida_del_cabello).
padecimiento(caida_del_cabello).
padecimiento(calambres).


%usado para
se_usa_en(canela,tónico).
se_usa_en(canela,té).
se_usa_en(cedron,cocimiento).
se_usa_en(cedron,agua_de_uso).
se_usa_en(cardo_santo,macerado).
se_usa_en(cardo_santo,lavados).
se_usa_en(cardo_santo,jugo_).
se_usa_en(cardo_santo,cocimiento).
%efecto
efecto(exita_el_apetito_sexual).
efecto(quita_o_modera_el_dolor).
efecto(insensibiliza_el_cuerpo).
efecto(controla_diarreas).
efecto(controla_espasmos_nerviosos).
efecto(ayuda_con_inflamaciones).
efecto(quita_la_fiebre).
efecto(mata_los_tejidos).
efecto(deseo_de_comer).
efecto(contrae_los_tejidos).
efecto(evita_formacion_de_gases).
efecto(ayuda_a_expulsar_la_bilis).
efecto(limpia_y_purifica_la_sangre).
efecto(provoca_sudoracion_como_cochino).
efecto(favorece_a_la_digestion).
efecto(provoca_la_orina).
efecto(provoca_nauseas_y_vomitos).
efecto(activa_la_menstruacion).
efecto(ayuda_a_tranquilizar).
efecto(detiene_las_hemorragias).
efecto(ayuda_al_higado).
efecto(purga_sin_provocar_diarrea).
efecto(ayuda_al_pecho).
efecto(calma_dolores_intestinales).
efecto(fortalece_el_organismo).
efecto(es_venenosa).
efecto(expulsa_gusanos_intestinales).
efecto(cura_llagas_y_heridas).

%se tarduce en
se_traduce_en(afrodisiaca,exita_el_apetito_sexual).
se_traduce_en(analgesica,quita_o_modera_el_dolor).
se_traduce_en(anestesica,insensibiliza_el_cuerpo).
se_traduce_en(antidiarreica,controla_diarreas).
se_traduce_en(antiespasmodica,controla_espasmos_nervioso).
se_traduce_en(antiflogistica,ayuda_con_inflamaciones).
se_traduce_en(antipiretica,quita_la_fiebre).
se_traduce_en(antiseptica,mata_los_tejidos).
se_traduce_en(aperitiva,deseo_de_comer).
se_traduce_en(astringente,contrae_los_tejidos).
se_traduce_en(carminativa,evita_formacion_de_gases).
se_traduce_en(colagoga,ayuda_a_expulsar_la_bilis).
se_traduce_en(depurativa,limpia_y_purifica_la_sangre).
se_traduce_en(diaforetica,provoca_sudoracion_como_cochino).
se_traduce_en(digestiva,favorece_a_la_digestion).
se_traduce_en(diuretica,provoca_la_orina).
se_traduce_en(emetica,provoca_nauseas_y_vomitos).
se_traduce_en(emenagoga,activa_la_menstruacion).
se_traduce_en(estupefaciente,ayuda_a_tranquilizar).
se_traduce_en(hemostatica,detiene_las_hemorragias).
se_traduce_en(hepatica,ayuda_al_higado).
se_traduce_en(laxante,purga_sin_provocar_diarrea).
se_traduce_en(pectoral,ayuda_al_pecho).
se_traduce_en(sedante,calma_dolores_intestinales).
se_traduce_en(tonica,fortalece_el_organismo).
se_traduce_en(toxica,es_venenosa).
se_traduce_en(vermifuga,expulsa_gusanos_intestinales).
se_traduce_en(vulneraria,cura_llagas_y_heridas).

%Principios activos
principios_activos(tonico_cardiaco).
principios_activos(morfina).
principios_activos(emetina).
principios_activos(estrienica).
principios_activos(veratrina).
principios_activos(colquicina).
principios_activos(atropina).
principios_activos(quina).
principios_activos(teobromina).
principios_activos(esparteina).
principios_activos(cocaina).
principios_activos(mescalina).
principios_activos(efedrina).
principios_activos(hormonas).
principios_activos(lutenurina).
principios_activos(tauremisina).
principios_activos(olitorisida).
principios_activos(acido_lisergico).
principios_activos(eucaliptol).
principios_activos(vitamina_c).
% produce
produce(digitaria,tonico_cardiaco).
produce(opio,morfina).
produce(ipeca,emetina).
produce(nuez vómica,estrienica).
produce(eleboro_blanco,veratrina).
produce(colchico,colquicina).
produce(belladona,atropina).
produce(quina,quina).
produce(cacao,teobromina).
produce(retama,esparteina).
produce(coca,cocaina).
produce(peyote,mescalina).
produce(efedra,efedrina).
produce(barrasco,hormonas).
produce(nenufar_amarillo,lutenurina).
produce(artemisa,tauremisina).
produce(semilla_de_yute,olitorisida).
produce(toloache,acido_lisergico).
produce(eucalipto,eucaliptol).
produce(rosal,vitamina_c).
%Tratamiento para
tratamiento_para(encina,sarpullido).
tratamiento_para(salvia,sarpullido).
tratamiento_para(tila,sarpullido).
tratamiento_para(limón,sed).
tratamiento_para(tamarindo,sed).
tratamiento_para(pirúl,sed).
tratamiento_para(semilla_de_calabaza,solitaria).
tratamiento_para(coquito_de_aceite,solitaria).
tratamiento_para(helecho_macho,solitaria).
tratamiento_para(encina,sudoración_escesiva).
tratamiento_para(alcanfor,tifoidea).
tratamiento_para(borraja,tifoidea).
tratamiento_para(quina_,tifoidea).
tratamiento_para(canela,tifoidea).
tratamiento_para(romero,tifoidea).
tratamiento_para(salvia,tifoidea).
tratamiento_para(berro_,tiña).
tratamiento_para(tamarindo,tiña).
tratamiento_para(salvia,tiña).
tratamiento_para(eucalipto,tos).
tratamiento_para(capulín,tos).
tratamiento_para(cedrón,tos).
tratamiento_para(salvia,tos).
tratamiento_para(malva,tos).
tratamiento_para(marrubio,tos).
tratamiento_para(gelsemio,tos_ferina).
tratamiento_para(quina,tos_ferina).
tratamiento_para(rábano,tos_ferina).
tratamiento_para(violeta,tos_ferina).
tratamiento_para(jugo_de_vástago_de_plátano_morado,tuberculosis).
tratamiento_para(mastuerzo,tuberculosis).
tratamiento_para(berro,tuberculosis).
tratamiento_para(ajo,tuberculosis).
tratamiento_para(eucalipto,tuberculosis).
tratamiento_para(pirúl,tuberculosis).
tratamiento_para(pino,tuberculosis).
tratamiento_para(roble,tuberculosis).
tratamiento_para(cuachalalate,úlcera).
tratamiento_para(sanguinaria,úlcera).
tratamiento_para(cola_de_caballo,úlcera).
tratamiento_para(girasol,úlcera).
tratamiento_para(limón,urticaria).
tratamiento_para(ruibarbo,urticaria).
tratamiento_para(hamamelis,várices).
tratamiento_para(castaño_de_indias,várices).
tratamiento_para(llanten,várices).
tratamiento_para(toronjil,várices).
tratamiento_para(apio,vejiga).
tratamiento_para(cipres,vejiga).
tratamiento_para(cola_de_caballo,vejiga).
tratamiento_para(ortiga,vejiga).
tratamiento_para(malva,vejiga).
tratamiento_para(leche_de_higuera,verrugas).
tratamiento_para(cebolla,verrugas).
tratamiento_para(nogal,verrugas).
tratamiento_para(albahaca,vértigos).
tratamiento_para(espino,vértigos).
tratamiento_para(menta,vómitos).
tratamiento_para(tila,vómitos).
tratamiento_para(marrubio,vómitos).
tratamiento_para(valeriana,vómitos).
tratamiento_para(salvia,vómitos).
tratamiento_para(cilantro,voz).
tratamiento_para(ajo,voz).
tratamiento_para(limón,voz).
tratamiento_para(pino,voz).
tratamiento_para(alfalfa,vitaminas).
tratamiento_para(espinacas,vitaminas).
tratamiento_para(acelga,vitaminas).
tratamiento_para(berro,vitaminas).
tratamiento_para(cebolla,vitaminas).
tratamiento_para(limón,vitaminas).
tratamiento_para(zanahoria,vitaminas).
tratamiento_para(verbena,lumbago).
tratamiento_para(fenogreco,llagas).
tratamiento_para(eucalipto,llagas).
tratamiento_para(llanten,llagas).
tratamiento_para(sanguinaria,llagas).
tratamiento_para(quina,malaria).
tratamiento_para(girasol,malaria).
tratamiento_para(eucalipto,malaria).
tratamiento_para(cardo,malaria).
tratamiento_para(azahar,menopausia).
tratamiento_para(hamamelis,menopausia).
tratamiento_para(tila,menopausia).
tratamiento_para(quina_roja,menopausia).
tratamiento_para(azafrán,menstruación).
tratamiento_para(hamamelis,menstruación).
tratamiento_para(belladona,menstruación).
tratamiento_para(anís_de_estrella,menstruación).
tratamiento_para(ruda,menstruación).
tratamiento_para(ajenjo,menstruación).
tratamiento_para(manzanilla,menstruación).
tratamiento_para(apio,menstruación).
tratamiento_para(hisopol,menstruación).
tratamiento_para(quina_amarilla,menstruación).
tratamiento_para(sabina,menstruación).
tratamiento_para(artemisa,menstruación).
tratamiento_para(hamamelis,metorragia).
tratamiento_para(zoapatle,metorragia).
tratamiento_para(perejil,metorragia).
tratamiento_para(cuercillo,metorragia).
tratamiento_para(clavo,muelas).
tratamiento_para(heidra,muelas).
tratamiento_para(ortiga,nariz).
tratamiento_para(cola_de_caballo,nariz).
tratamiento_para(ruda,nariz).
tratamiento_para(eucalipto,nariz).
tratamiento_para(anís,náuseas).
tratamiento_para(ajenjo,náuseas).
tratamiento_para(menta,náuseas).
tratamiento_para(salvia,náuseas).
tratamiento_para(manzanilla,neuralgias).
tratamiento_para(menta,neuralgias).
tratamiento_para(valeriana,neuralgias).
tratamiento_para(bolde,neuralgias).
tratamiento_para(rasiflora,neurastenia).
tratamiento_para(té_negro,neurastenia).
tratamiento_para(mate,neurastenia).
tratamiento_para(valeriana,neurastenia).
tratamiento_para(linaza,nefritis).
tratamiento_para(grama,nefritis).
tratamiento_para(cebada,nefritis).
tratamiento_para(llanten,nefritis).
tratamiento_para(doradilla,nefritis).
tratamiento_para(espárrago_ruda,nefritis).
tratamiento_para(toronjil,obesidad).
tratamiento_para(marrubio,obesidad).
tratamiento_para(limón,obesidad).
tratamiento_para(malva,obesidad).
tratamiento_para(esparrago,obesidad).
tratamiento_para(boldo,oídos).
tratamiento_para(aceite_de_oliva,oídos).
tratamiento_para(llanten,oídos).
tratamiento_para(hiedra,oídos).
tratamiento_para(manzanilla,conjuntivitis).
tratamiento_para(limón,conjuntivitis).
tratamiento_para(llanten,conjuntivitis).
tratamiento_para(salvia,conjuntivitis).
tratamiento_para(ruda,conjuntivitis).
tratamiento_para(rosal,conjuntivitis).
tratamiento_para(ajenjo,paludismo).
tratamiento_para(quina,paludismo).
tratamiento_para(berros,pecas).
tratamiento_para(genciana_,pecas).
tratamiento_para(rabano,pecas).
tratamiento_para(papaija,pecas).
tratamiento_para(laurel,pies_olorosos).
tratamiento_para(encina,pies_olorosos).
tratamiento_para(miel,piquetes).
tratamiento_para(perejil,piquetes).
tratamiento_para(cebolla,piquetes).
tratamiento_para(puerro,piquetes).
tratamiento_para(fresno,piquetes).
tratamiento_para(ipecacuana,piquetes).
tratamiento_para(alcanfor,piquetes).
tratamiento_para(perejil,piquetes).
tratamiento_para(hamamelis,piquetes).
tratamiento_para(anagálida,piquetes).
tratamiento_para(jengibre,pleuresia).
tratamiento_para(linaza,pleuresia).
tratamiento_para(cardo,pleuresia).
tratamiento_para(girasol,pleuresia).
tratamiento_para(ipecacuana,piorrea).
tratamiento_para(cola_de_caballo,próstata).
tratamiento_para(eucalipto,pulmonía).
tratamiento_para(ocote,pulmonía).
tratamiento_para(gordolobo,pulmonía).
tratamiento_para(borraja,pulmonía).
tratamiento_para(sauco,pulmonía).
tratamiento_para(linaza,quemaduras).
tratamiento_para(cebolla,quemaduras).
tratamiento_para(hiedra,quemaduras).
tratamiento_para(gordolobo,quemaduras).
tratamiento_para(nogal,raquitismo).
tratamiento_para(ajo,reumatismo).
tratamiento_para(apio,reumatismo).
tratamiento_para(borraja,reumatismo).
tratamiento_para(gobernadora,reumatismo).
tratamiento_para(pino,reumatismo).
tratamiento_para(romero,reumatismo).
tratamiento_para(sanguinaria,reumatismo).
tratamiento_para(marrubio,reumatismo).
tratamiento_para(tabaco,reumatismo).
tratamiento_para(cabellos_de_elote,riñones).
tratamiento_para(cola_de_caballo,riñones).
tratamiento_para(apio,riñones).
tratamiento_para(eucalipto,ronquera).
tratamiento_para(pino,ronquera).
tratamiento_para(gordolobo,ronquera).
tratamiento_para(ajo,ronquera).
tratamiento_para(cebolla,ronquera).
tratamiento_para(estafiate,san_vito).
tratamiento_para(valeriana,san_vito).
tratamiento_para(borraja,sarampión).
tratamiento_para(ortiga,sarampión).
tratamiento_para(sauco,sarampión).
tratamiento_para(ajo,sarna).
tratamiento_para(alcanfor,sarna).
tratamiento_para(menta,sarna).
tratamiento_para(tomillo,sarna).
tratamiento_para(romero,sarna).
tratamiento_para(ármica,flebitis).
tratamiento_para(alfalfa_,flebitis).
tratamiento_para(lino,flebitis).
tratamiento_para(malvavisco,flebitis).
tratamiento_para(romero,flebitis).
tratamiento_para(quina,flebitis).
tratamiento_para(genciana_,flemas).
tratamiento_para(orégano,flemas).
tratamiento_para(fenogreco,forúnculos).
tratamiento_para(malvavisco,forúnculos).
tratamiento_para(hiedra,forúnculos).
tratamiento_para(manzanilla,gastralgia).
tratamiento_para(anís_de_estrella,gastralgia).
tratamiento_para(cola_de_caballo,gonorrea).
tratamiento_para(doradilla,gonorrea).
tratamiento_para(zarzaparrilla,gonorrea).
tratamiento_para(apio,gota).
tratamiento_para(cerezo,gota).
tratamiento_para(limón,gota).
tratamiento_para(pino,gota).
tratamiento_para(alcanfor,gota).
tratamiento_para(aconito,gota).
tratamiento_para(belladona,gota).
tratamiento_para(beleño,gota).
tratamiento_para(colchico,gota).
tratamiento_para(chicalote,gota).
tratamiento_para(encina,grietas_del_ano).
tratamiento_para(encina,grietas_del_pezón).
tratamiento_para(nogal,grietas_del_pezón).
tratamiento_para(milenrana,grietas_del_pezón).
tratamiento_para(eucalipto,gripe).
tratamiento_para(limón,gripe).
tratamiento_para(quina,gripe).
tratamiento_para(zarzaparrilla,gripe).
tratamiento_para(calendula,gripe).
tratamiento_para(hinojo,halitosis).
tratamiento_para(menta,halitosis).
tratamiento_para(mastuerzo,hemorraga_interna).
tratamiento_para(ortiga,hemorraga_interna).
tratamiento_para(rosal,hemorraga_interna).
tratamiento_para(retama,hepatitis).
tratamiento_para(boldo,hepatitis).
tratamiento_para(alcachofa,hepatitis).
tratamiento_para(prodigiosa,hepatitis).
tratamiento_para(cáscara_sagrada,hepatitis).
tratamiento_para(helecho,hernia).
tratamiento_para(ricino,hernia).
tratamiento_para(tabaco,hernia).
tratamiento_para(linaza,herpes).
tratamiento_para(llanten,herpes).
tratamiento_para(árnica_,heridas).
tratamiento_para(hamamelis,heridas).
tratamiento_para(alcachofa,hidropesia).
tratamiento_para(cardo,hidropesia).
tratamiento_para(perejil,hidropesia).
tratamiento_para(sauco,hidropesia).
tratamiento_para(berros,hidropesia).
tratamiento_para(retama,hidropesia).
tratamiento_para(marrubio,congestion_en_el_higado).
tratamiento_para(boldo,congestion_en_el_higado).
tratamiento_para(doradilla,congestion_en_el_higado).
tratamiento_para(ruibarbo,congestion_en_el_higado).
tratamiento_para(manzanilla,colico).
tratamiento_para(lechuga,bilis).
tratamiento_para(tila,bilis).
tratamiento_para(papoloquelite,letericia).
tratamiento_para(achicoria,letericia).
tratamiento_para(berros,letericia).
tratamiento_para(llanten,letericia).
tratamiento_para(retama,letericia).
tratamiento_para(tecomasuchil,letericia).
tratamiento_para(ajo,hipertensión).
tratamiento_para(esparrago,hipertensión).
tratamiento_para(alpiste,hipertensión).
tratamiento_para(muerdago,hipertensión).
tratamiento_para(miel,hipotensión).
tratamiento_para(nuez_de_kola,hipotensión).
tratamiento_para(crategus,hipotensión).
tratamiento_para(acedera,hipotensión).
tratamiento_para(anís,hipo).
tratamiento_para(hinojo,hipo).
tratamiento_para(tila,hipo).
tratamiento_para(valeriana,hipo).
tratamiento_para(azahar,histerismo).
tratamiento_para(beleño,histerismo).
tratamiento_para(gelsenio,histerismo).
tratamiento_para(tila,histerismo).
tratamiento_para(valeriana,histerismo).
tratamiento_para(pastiflora,insómio).
tratamiento_para(azahar,insómio).
tratamiento_para(menta,insómio).
tratamiento_para(manzanilla,insómio).
tratamiento_para(lechuga,insómio).
tratamiento_para(genciana_,intestino).
tratamiento_para(melisa,intestino).
tratamiento_para(yohimbo,impotencia_sexual).
tratamiento_para(damiana,impotencia_sexual).
tratamiento_para(nuex_vómica,impotencia_sexual).
tratamiento_para(aguacate,impotencia_sexual).
tratamiento_para(manzanilla,jaqueca).
tratamiento_para(acónito,jaqueca).
tratamiento_para(valeriana,jaqueca).
tratamiento_para(tila,jaqueca).
tratamiento_para(chicalote,jaqueca).
tratamiento_para(hinojo,lactancia).
tratamiento_para(anís,lactancia).
tratamiento_para(menta,lactancia).
tratamiento_para(perejil,lactancia).
tratamiento_para(zanahoria,lactancia).
tratamiento_para(acónito,laringitis).
tratamiento_para(borraja,laringitis).
tratamiento_para(cebolla,laringitis).
tratamiento_para(rosal,laringitis).
tratamiento_para(benjui,laringitis).
tratamiento_para(encina,laringitis).
tratamiento_para(encina,leucorrea).
tratamiento_para(zarzaparrilla,leucorrea).
tratamiento_para(pino,leucorrea).
tratamiento_para(enebro,leucorrea).
tratamiento_para(genciana_,leucorrea).
tratamiento_para(ajenjo,lombrices).
tratamiento_para(ajo,lombrices).
tratamiento_para(cebolla,lombrices).
tratamiento_para(brionia,lombrices).
tratamiento_para(aguacate,lombrices).
tratamiento_para(papaya,lombrices).
tratamiento_para(avena,lumbago).
tratamiento_para(cebada,lumbago).
tratamiento_para(tomillo,lumbago).
tratamiento_para(borraja,reumatismo).
tratamiento_para(gobernadora,reumatismo).
tratamiento_para(pino,reumatismo).
tratamiento_para(romero,reumatismo).
tratamiento_para(sanguinaria,reumatismo).
tratamiento_para(marrubio,reumatismo).
tratamiento_para(tabaco,reumatismo).
tratamiento_para(cabellos_de_elote,riñones).
tratamiento_para(cola_de_caballo,riñones).
tratamiento_para(apio,riñones).
tratamiento_para(eucalipto,ronquera).
tratamiento_para(pino,ronquera).
tratamiento_para(gordolobo,ronquera).
tratamiento_para(ajo,ronquera).
tratamiento_para(cebolla,ronquera).
tratamiento_para(estafiate,san_vito).
tratamiento_para(valeriana,san_vito).
tratamiento_para(borraja,sarampión).
tratamiento_para(ortiga,sarampión).
tratamiento_para(sauco,sarampión).
tratamiento_para(ajo,sarna).
tratamiento_para(alcanfor,sarna).
tratamiento_para(menta,sarna).
tratamiento_para(tomillo,sarna).
tratamiento_para(romero,sarna).
tratamiento_para(encina,sarpullido).
tratamiento_para(salvia,sarpullido).
tratamiento_para(tila,sarpullido).
tratamiento_para(limón,sed).
tratamiento_para(tamarindo,sed).
tratamiento_para(pirúl,sed).
tratamiento_para(semilla_de_calabaza,solitaria).
tratamiento_para(coquito_de_aceite,solitaria).
tratamiento_para(helecho_macho,solitaria).
tratamiento_para(encina,sudoración_escesiva).
tratamiento_para(alcanfor,tifoidea).
tratamiento_para(borraja,tifoidea).
tratamiento_para(quina_,tifoidea).
tratamiento_para(canela,tifoidea).
tratamiento_para(romero,tifoidea).
tratamiento_para(salvia,tifoidea).
tratamiento_para(berro_,tiña).
tratamiento_para(tamarindo,tiña).
tratamiento_para(salvia,tiña).
tratamiento_para(eucalipto,tos).
tratamiento_para(capulín,tos).
tratamiento_para(cedrón,tos).
tratamiento_para(salvia,tos).
tratamiento_para(malva,tos).
tratamiento_para(marrubio,tos).
tratamiento_para(gelsemio,tos_ferina).
tratamiento_para(quina,tos_ferina).
tratamiento_para(rábano,tos_ferina).
tratamiento_para(violeta,tos_ferina).
tratamiento_para(jugo_de_vástago_de_plátano_morado,tuberculosis).
tratamiento_para(mastuerzo,tuberculosis).
tratamiento_para(berro,tuberculosis).
tratamiento_para(ajo,tuberculosis).
tratamiento_para(eucalipto,tuberculosis).
tratamiento_para(pirúl,tuberculosis).
tratamiento_para(pino,tuberculosis).
tratamiento_para(roble,tuberculosis).
tratamiento_para(cuachalalate,úlcera).
tratamiento_para(sanguinaria,úlcera).
tratamiento_para(cola_de_caballo,úlcera).
tratamiento_para(girasol,úlcera).
tratamiento_para(limón,urticaria).
tratamiento_para(ruibarbo,urticaria).
tratamiento_para(hamamelis,várices).
tratamiento_para(castaño_de_indias,várices).
tratamiento_para(llanten,várices).
tratamiento_para(toronjil,várices).
tratamiento_para(apio,vejiga).
tratamiento_para(cipres,vejiga).
tratamiento_para(cola_de_caballo,vejiga).
tratamiento_para(ortiga,vejiga).
tratamiento_para(malva,vejiga).
tratamiento_para(leche_de_higuera,verrugas).
tratamiento_para(cebolla,verrugas).
tratamiento_para(nogal,verrugas).
tratamiento_para(albahaca,vértigos).
tratamiento_para(espino,vértigos).
tratamiento_para(menta,vómitos).
tratamiento_para(tila,vómitos).
tratamiento_para(marrubio,vómitos).
tratamiento_para(valeriana,vómitos).
tratamiento_para(salvia,vómitos).
tratamiento_para(cilantro,voz).
tratamiento_para(ajo,voz).
tratamiento_para(limón,voz).
tratamiento_para(pino,voz).
tratamiento_para(alfalfa,vitaminas).
tratamiento_para(espinacas,vitaminas).
tratamiento_para(acelga,vitaminas).
tratamiento_para(berro,vitaminas).
tratamiento_para(cebolla,vitaminas).
tratamiento_para(limón,vitaminas).
tratamiento_para(zanahoria,vitaminas).
tratamiento_para(avena,lumbago).
tratamiento_para(cebada,lumbago).
tratamiento_para(tomillo,lumbago).
tratamiento_para(verbena,lumbago).
tratamiento_para(fenogreco,llagas).
tratamiento_para(eucalipto,llagas).
tratamiento_para(llanten,llagas).
tratamiento_para(sanguinaria,llagas).
tratamiento_para(quina,malaria).
tratamiento_para(girasol,malaria).
tratamiento_para(eucalipto,malaria).
tratamiento_para(cardo,malaria).
tratamiento_para(azahar,menopausia).
tratamiento_para(hamamelis,menopausia).
tratamiento_para(tila,menopausia).
tratamiento_para(quina_roja,menopausia).
tratamiento_para(azafrán,menstruación).
tratamiento_para(hamamelis,menstruación).
tratamiento_para(belladona,menstruación).
tratamiento_para(anís_de_estrella,menstruación).
tratamiento_para(ruda,menstruación).
tratamiento_para(ajenjo,menstruación).
tratamiento_para(manzanilla,menstruación).
tratamiento_para(apio,menstruación).
tratamiento_para(hisopol,menstruación).
tratamiento_para(quina_amarilla,menstruación).
tratamiento_para(sabina,menstruación).
tratamiento_para(artemisa,menstruación).
tratamiento_para(hamamelis,metorragia).
tratamiento_para(zoapatle,metorragia).
tratamiento_para(perejil,metorragia).
tratamiento_para(cuercillo,metorragia).
tratamiento_para(clavo,muelas).
tratamiento_para(heidra,muelas).
tratamiento_para(ortiga,nariz).
tratamiento_para(cola_de_caballo,nariz).
tratamiento_para(ruda,nariz).
tratamiento_para(eucalipto,nariz).
tratamiento_para(anís,náuseas).
tratamiento_para(ajenjo,náuseas).
tratamiento_para(menta,náuseas).
tratamiento_para(salvia,náuseas).
tratamiento_para(manzanilla,neuralgias).
tratamiento_para(menta,neuralgias).
tratamiento_para(valeriana,neuralgias).
tratamiento_para(bolde,neuralgias).
tratamiento_para(rasiflora,neurastenia).
tratamiento_para(té_negro,neurastenia).
tratamiento_para(mate,neurastenia).
tratamiento_para(valeriana,neurastenia).
tratamiento_para(linaza,nefritis).
tratamiento_para(grama,nefritis).
tratamiento_para(cebada,nefritis).
tratamiento_para(llanten,nefritis).
tratamiento_para(doradilla,nefritis).
tratamiento_para(espárrago_ruda,nefritis).
tratamiento_para(toronjil,obesidad).
tratamiento_para(marrubio,obesidad).
tratamiento_para(limón,obesidad).
tratamiento_para(malva,obesidad).
tratamiento_para(esparrago,obesidad).
tratamiento_para(boldo,oídos).
tratamiento_para(aceite_de_oliva,oídos).
tratamiento_para(llanten,oídos).
tratamiento_para(hiedra,oídos).
tratamiento_para(manzanilla,conjuntivitis).
tratamiento_para(limón,conjuntivitis).
tratamiento_para(llanten,conjuntivitis).
tratamiento_para(salvia,conjuntivitis).
tratamiento_para(ruda,conjuntivitis).
tratamiento_para(rosal,conjuntivitis).
tratamiento_para(ajenjo,paludismo).
tratamiento_para(quina,paludismo).
tratamiento_para(berros,pecas).
tratamiento_para(genciana_,pecas).
tratamiento_para(rabano,pecas).
tratamiento_para(papaija,pecas).
tratamiento_para(laurel,pies_olorosos).
tratamiento_para(encina,pies_olorosos).
tratamiento_para(miel,piquetes).
tratamiento_para(perejil,piquetes).
tratamiento_para(cebolla,piquetes).
tratamiento_para(puerro,piquetes).
tratamiento_para(fresno,piquetes).
tratamiento_para(ipecacuana,piquetes).
tratamiento_para(alcanfor,piquetes).
tratamiento_para(perejil,piquetes).
tratamiento_para(hamamelis,piquetes).
tratamiento_para(anagálida,piquetes).
tratamiento_para(jengibre,pleuresia).
tratamiento_para(linaza,pleuresia).
tratamiento_para(cardo,pleuresia).
tratamiento_para(girasol,pleuresia).
tratamiento_para(ipecacuana,piorrea).
tratamiento_para(cola_de_caballo,próstata).
tratamiento_para(eucalipto,pulmonía).
tratamiento_para(ocote,pulmonía).
tratamiento_para(gordolobo,pulmonía).
tratamiento_para(borraja,pulmonía).
tratamiento_para(sauco,pulmonía).
tratamiento_para(linaza,quemaduras).
tratamiento_para(cebolla,quemaduras).
tratamiento_para(hiedra,quemaduras).
tratamiento_para(gordolobo,quemaduras).
tratamiento_para(nogal,raquitismo).
tratamiento_para(ajo,reumatismo).
tratamiento_para(apio,reumatismo).
tratamiento_para(pino,gota).
tratamiento_para(alcanfor,gota).
tratamiento_para(aconito,gota).
tratamiento_para(belladona,gota).
tratamiento_para(beleño,gota).
tratamiento_para(colchico,gota).
tratamiento_para(chicalote,gota).
tratamiento_para(encina,grietas_del_ano).
tratamiento_para(encina,grietas_del_pezón).
tratamiento_para(nogal,grietas_del_pezón).
tratamiento_para(milenrana,grietas_del_pezón).
tratamiento_para(eucalipto,gripe).
tratamiento_para(limón,gripe).
tratamiento_para(quina,gripe).
tratamiento_para(zarzaparrilla,gripe).
tratamiento_para(calendula,gripe).
tratamiento_para(hinojo,halitosis).
tratamiento_para(menta,halitosis).
tratamiento_para(mastuerzo,hemorraga_interna).
tratamiento_para(ortiga,hemorraga_interna).
tratamiento_para(rosal,hemorraga_interna).
tratamiento_para(retama,hepatitis).
tratamiento_para(boldo,hepatitis).
tratamiento_para(alcachofa,hepatitis).
tratamiento_para(prodigiosa,hepatitis).
tratamiento_para(cáscara_sagrada,hepatitis).
tratamiento_para(helecho,hernia).
tratamiento_para(ricino,hernia).
tratamiento_para(tabaco,hernia).
tratamiento_para(linaza,herpes).
tratamiento_para(llanten,herpes).
tratamiento_para(árnica_,heridas).
tratamiento_para(hamamelis,heridas).
tratamiento_para(alcachofa,hidropesia).
tratamiento_para(cardo,hidropesia).
tratamiento_para(perejil,hidropesia).
tratamiento_para(sauco,hidropesia).
tratamiento_para(berros,hidropesia).
tratamiento_para(retama,hidropesia).
tratamiento_para(marrubio,congestion_en_el_higado).
tratamiento_para(boldo,congestion_en_el_higado).
tratamiento_para(doradilla,congestion_en_el_higado).
tratamiento_para(ruibarbo,congestion_en_el_higado).
tratamiento_para(manzanilla,colico).
tratamiento_para(lechuga,bilis).
tratamiento_para(tila,bilis).
tratamiento_para(papoloquelite,letericia).
tratamiento_para(achicoria,letericia).
tratamiento_para(berros,letericia).
tratamiento_para(llanten,letericia).
tratamiento_para(retama,letericia).
tratamiento_para(tecomasuchil,letericia).
tratamiento_para(ajo,hipertensión).
tratamiento_para(esparrago,hipertensión).
tratamiento_para(alpiste,hipertensión).
tratamiento_para(muerdago,hipertensión).
tratamiento_para(miel,hipotensión).
tratamiento_para(nuez_de_kola,hipotensión).
tratamiento_para(crategus,hipotensión).
tratamiento_para(acedera,hipotensión).
tratamiento_para(anís,hipo).
tratamiento_para(hinojo,hipo).
tratamiento_para(tila,hipo).
tratamiento_para(valeriana,hipo).
tratamiento_para(azahar,histerismo).
tratamiento_para(beleño,histerismo).
tratamiento_para(gelsenio,histerismo).
tratamiento_para(tila,histerismo).
tratamiento_para(valeriana,histerismo).
tratamiento_para(pastiflora,insómio).
tratamiento_para(azahar,insómio).
tratamiento_para(menta,insómio).
tratamiento_para(manzanilla,insómio).
tratamiento_para(lechuga,insómio).
tratamiento_para(genciana_,intestino).
tratamiento_para(melisa,intestino).
tratamiento_para(yohimbo,impotencia_sexual).
tratamiento_para(damiana,impotencia_sexual).
tratamiento_para(nuex_vómica,impotencia_sexual).
tratamiento_para(aguacate,impotencia_sexual).
tratamiento_para(manzanilla,jaqueca).
tratamiento_para(acónito,jaqueca).
tratamiento_para(valeriana,jaqueca).
tratamiento_para(tila,jaqueca).
tratamiento_para(chicalote,jaqueca).
tratamiento_para(hinojo,lactancia).
tratamiento_para(anís,lactancia).
tratamiento_para(menta,lactancia).
tratamiento_para(perejil,lactancia).
tratamiento_para(zanahoria,lactancia).
tratamiento_para(acónito,laringitis).
tratamiento_para(borraja,laringitis).
tratamiento_para(cebolla,laringitis).
tratamiento_para(rosal,laringitis).
tratamiento_para(benjui,laringitis).
tratamiento_para(encina,laringitis).
tratamiento_para(encina,leucorrea).
tratamiento_para(zarzaparrilla,leucorrea).
tratamiento_para(pino,leucorrea).
tratamiento_para(enebro,leucorrea).
tratamiento_para(genciana_,leucorrea).
tratamiento_para(ajenjo,lombrices).
tratamiento_para(ajo,lombrices).
tratamiento_para(cebolla,lombrices).
tratamiento_para(brionia,lombrices).
tratamiento_para(aguacate,lombrices).
tratamiento_para(papaya,lombrices).
tratamiento_para(briania,contusiones).
tratamiento_para(digital,corazón).
tratamiento_para(salvia,corazón).
tratamiento_para(nuez_de_kcla,corazón).
tratamiento_para(tejocote,corazón).
tratamiento_para(achicoria,depurativos_de_la_sangre).
tratamiento_para(diente_de_león,depurativos_de_la_sangre).
tratamiento_para(apio,depurativos_de_la_sangre).
tratamiento_para(sanguinaria,depurativos_de_la_sangre).
tratamiento_para(zarzaparrilla,depurativos_de_la_sangre).
tratamiento_para(berro,depurativos_de_la_sangre).
tratamiento_para(matarique,diabetes).
tratamiento_para(tronadora,diabetes).
tratamiento_para(bucalipto,diabetes).
tratamiento_para(damiana,diabetes).
tratamiento_para(capulín,diarrea_crónica).
tratamiento_para(mezquite,diarrea_crónica).
tratamiento_para(tlalchichinole,diarrea_crónica).
tratamiento_para(linaza,diarrea_por_irritación).
tratamiento_para(membrillo,diarrea_por_irritación).
tratamiento_para(arroz,diarrea_por_irritación).
tratamiento_para(cebada,diarrea_por_irritación).
tratamiento_para(guayaba,diarrea_por_inflamación).
tratamiento_para(albahaca,diarrea_por_inflamación).
tratamiento_para(granada,diarrea_por_inflamación).
tratamiento_para(manzanilla,diarrea_verdosa).
tratamiento_para(sinionillo,diarrea_verdosa).
tratamiento_para(siempreviva,diarrea_verdosa).
tratamiento_para(chaparro_amargoso,diarrea_con_sangre).
tratamiento_para(muicle,diarrea_con_sangre).
tratamiento_para(monacillo,diarrea_con_sangre).
tratamiento_para(limón,difteria).
tratamiento_para(naranja,difteria).
tratamiento_para(tamarindo,disentería).
tratamiento_para(chaparro_amargoso,disentería).
tratamiento_para(ipecacuana,disentería).
tratamiento_para(cedrón,disentería).
tratamiento_para(anís,dispepsia).
tratamiento_para(menta,dispepsia).
tratamiento_para(yerbabuena,dispepsia).
tratamiento_para(diente_de_león,dispepsia).
tratamiento_para(té_de_limón,dispepsia).
tratamiento_para(quina,dispepsia).
tratamiento_para(genciana_,dispepsia).
tratamiento_para(tabequillo,dispepsia).
tratamiento_para(ruibaxbo,dispepsia).
tratamiento_para(anís_estrella,dolor).
tratamiento_para(valeriana,dolor).
tratamiento_para(manzanilla,dolor).
tratamiento_para(alcanfor,dolores_musculares).
tratamiento_para(tamarindo,empacho).
tratamiento_para(linaza,enteritis).
tratamiento_para(cedrón,enteritis).
tratamiento_para(llanten,enteritis).
tratamiento_para(valeriana,epilepsia).
tratamiento_para(hierba_del_pollo,epistaxis).
tratamiento_para(cebolla,epistaxis).
tratamiento_para(perejil,epistaxis).
tratamiento_para(sauco,erisipela).
tratamiento_para(hiedra,erisipela).
tratamiento_para(zanahoria,erisipela).
tratamiento_para(borraja,escarlatina).
tratamiento_para(sauco,escarlatina).
tratamiento_para(cebolla,escarlatina).
tratamiento_para(ajo,escorbuto).
tratamiento_para(limón,escorbuto).
tratamiento_para(berro,escorbuto).
tratamiento_para(cebolla,escorbuto).
tratamiento_para(geranio,escorbuto).
tratamiento_para(ciruela,estreñimiento).
tratamiento_para(linaza,estreñimiento).
tratamiento_para(chía,estreñimiento).
tratamiento_para(tamarindo,estreñimiento).
tratamiento_para(agar-agar,estreñimiento).
tratamiento_para(eucalipto,faringitis).
tratamiento_para(lavanda,faringitis).
tratamiento_para(anacahuite,faringitis).
tratamiento_para(apio,flatulencia).
tratamiento_para(tomillo,flatulencia).
tratamiento_para(perejil,flatulencia).
tratamiento_para(anís,flatulencia).
tratamiento_para(hinojo,flatulencia).
tratamiento_para(toronjil,flatulencia).
tratamiento_para(romero,flatulencia).
tratamiento_para(ruibarbo,flatulencia).
tratamiento_para(ruda,flatulencia).
tratamiento_para(menta,flatulencia).
tratamiento_para(ármica,flebitis).
tratamiento_para(alfalfa_,flebitis).
tratamiento_para(lino,flebitis).
tratamiento_para(malvavisco,flebitis).
tratamiento_para(romero,flebitis).
tratamiento_para(quina,flebitis).
tratamiento_para(genciana_,flemas).
tratamiento_para(orégano,flemas).
tratamiento_para(fenogreco,forúnculos).
tratamiento_para(malvavisco,forúnculos).
tratamiento_para(hiedra,forúnculos).
tratamiento_para(manzanilla,gastralgia).
tratamiento_para(anís_de_estrella,gastralgia).
tratamiento_para(cola_de_caballo,gonorrea).
tratamiento_para(doradilla,gonorrea).
tratamiento_para(zarzaparrilla,gonorrea).
tratamiento_para(apio,gota).
tratamiento_para(cerezo,gota).
tratamiento_para(limón,gota).
tratamiento_para(laurel,contusiones).
tratamiento_para(arnica,almorranas).
tratamiento_para(sauco,almorranas).
tratamiento_para(ajenjo_,anemia).
tratamiento_para(germen_de_trigo,anemia).
tratamiento_para(quira,anemia).
tratamiento_para(canela,anemia).
tratamiento_para(alholva,anemia).
tratamiento_para(eucalipto,anginas).
tratamiento_para(cebada,anginas).
tratamiento_para(salvia,anginas).
tratamiento_para(tabachin,anginas).
tratamiento_para(borraja,anginas).
tratamiento_para(ajenjo_,anorexia).
tratamiento_para(gerciana,anorexia).
tratamiento_para(yerbabuena,anorexia).
tratamiento_para(limón,arterosclerosis).
tratamiento_para(genciana_,arterosclerosis).
tratamiento_para(cardo,arterosclerosis).
tratamiento_para(zarzaparrilla,arterosclerosis).
tratamiento_para(arnica,arterosclerosis).
tratamiento_para(chicalote,arterosclerosis).
tratamiento_para(alcanfor,arterosclerosis).
tratamiento_para(toronja,arterosclerosis).
tratamiento_para(limón,artritis).
tratamiento_para(genciana_,artritis).
tratamiento_para(cardo,artritis).
tratamiento_para(zarzaparrilla,artritis).
tratamiento_para(arnica,artritis).
tratamiento_para(chicalote,artritis).
tratamiento_para(alcanfor,artritis).
tratamiento_para(toronja,artritis).
tratamiento_para(eucalipto,asma).
tratamiento_para(merrubio,asma).
tratamiento_para(toloache,asma).
tratamiento_para(oregano,asma).
tratamiento_para(salvia,asma).
tratamiento_para(lupulo,atonia_estomacal).
tratamiento_para(eucalipto,atonia_estomacal).
tratamiento_para(cuasia,atonia_estomacal).
tratamiento_para(uva_,bazo).
tratamiento_para(cerezo,bazo).
tratamiento_para(malva,inflamación_de_la_boca).
tratamiento_para(rosal,inflamación_de_la_boca).
tratamiento_para(limón,inflamación_de_la_boca).
tratamiento_para(salvia,inflamación_de_la_boca).
tratamiento_para(rosal,estomatitis).
tratamiento_para(encina,estomatitis).
tratamiento_para(salvia,estomatitis).
tratamiento_para(zarzamora,estomatitis).
tratamiento_para(eucalipto,bronquitis).
tratamiento_para(borraga,bronquitis).
tratamiento_para(anacahuite,bronquitis).
tratamiento_para(gordolobo,bronquitis).
tratamiento_para(tilo,bronquitis).
tratamiento_para(benjui,bronquitis).
tratamiento_para(marrubio,bronquitis).
tratamiento_para(rabano,bronquitis).
tratamiento_para(gordolobo,bronconeumonia).
tratamiento_para(eucalipto,bronconeumonia).
tratamiento_para(ipecacuana,bronconeumonia).
tratamiento_para(mostaza,bronconeumonia).
tratamiento_para(ortiga,caida_del_cabello).
tratamiento_para(espinosilla,caida_del_cabello).
tratamiento_para(marrubio,caida_del_cabello).
tratamiento_para(romero,caida_del_cabello).
tratamiento_para(anís,calambres).
tratamiento_para(tila,calambres).
tratamiento_para(manzanilla,calambres).
tratamiento_para(ajenjo_,calambres).
tratamiento_para(diente_de_león,cálculos_biliares).
tratamiento_para(aceite_de_oliva,cálculos_biliares).
tratamiento_para(retama,cálculos_biliares).
tratamiento_para(cabellos_de_elote,cálculos_renales).
tratamiento_para(pinguica_,cálculos_renales).
tratamiento_para(cola_de_caballo,cálculos_renales).
tratamiento_para(ajo,callos).
tratamiento_para(cebolla,callos).
tratamiento_para(hiedra,caries).
tratamiento_para(cola_de_caballo,caries).
tratamiento_para(ortiga,caspa).
tratamiento_para(limón,caspa).
tratamiento_para(romero,caspa).
tratamiento_para(cuachalalate,cancer_de_útero).
tratamiento_para(llanten,cancer_de_útero).
tratamiento_para(siempreviva,cancer_de_útero).
tratamiento_para(mastuerzo,ciática).
tratamiento_para(higuera,ciática).
tratamiento_para(sauco,ciática).
tratamiento_para(toronjil,circulación).
tratamiento_para(sanguinaria,circulación).
tratamiento_para(salvia,circulación).
tratamiento_para(hamamelis,circulación).
tratamiento_para(cola_de_caballo,cistitis).
tratamiento_para(doradilla,cistitis).
tratamiento_para(ajo,cistitis).
tratamiento_para(cabellos_de_elote,cistitis).
tratamiento_para(menta,cólicos).
tratamiento_para(hinojo,cólicos).
tratamiento_para(manzanilla,cólicos).
tratamiento_para(toronjil,cólicos).
tratamiento_para(boldo,cólicos).
tratamiento_para(linaza,colitis).
tratamiento_para(anís,colitis).
tratamiento_para(romero,colitis).
tratamiento_para(cola_de_caballo,colitis).
tratamiento_para(árnica_,contusiones).
tratamiento_para(hamamelis,contusiones).
tratamiento_para(malva,abscesos).
tratamiento_para(zarzaparrilla,absceso_hepático).
tratamiento_para(anís,acidez_estomacal).
tratamiento_para(perejil,acidez_estomacal).
tratamiento_para(sanguinaria,ácido_úrico).
tratamiento_para(limon,ácido_úrico).
tratamiento_para(sauco,ácido_úrico).
tratamiento_para(árnica,acné).
tratamiento_para(llanten,aftas).
tratamiento_para(fenogreco,aftas).
tratamiento_para(zarzamora,aftas).
tratamiento_para(salvia,agotamiento).
tratamiento_para(tilo,agotamiento).
tratamiento_para(valeriana,agotamiento).
tratamiento_para(yerbabuena,agruras).
tratamiento_para(manzanilla,agruras).
tratamiento_para(jugo_de_limón,agruras).
tratamiento_para(jugo_de_toronja,agruras).
tratamiento_para(pingüica,albuminaria).
tratamiento_para(quinoa_roja,albuminaria).
tratamiento_para(encino_rojo,albuminaria).
tratamiento_para(pimiento,alcoholismo).
tratamiento_para(salvia,almorranas).
tratamiento_para(huramelis,almorranas).
tratamiento_para(sanguinaria,almorranas).
tratamiento_para(cola_de_caballo,almorranas).
tratamiento_para(canela,anemia).
tratamiento_para(canela,debilidad).
tratamiento_para(canela,gripe).
tratamiento_para(canela,gases).
tratamiento_para(canela,mala_digestion).
tratamiento_para(cedron,colicos).
tratamiento_para(cedron,nauseas).
tratamiento_para(cedron,flatulencias).
tratamiento_para(cedron,mala_digestion).
tratamiento_para(cardo_santo,nubes_en_los_ojos).


tratamiento_para(abrojo,afecciones_del_pecho). 
tratamiento_para(abrojo,inflamacion_de_los_ojos). 
tratamiento_para(abrojo,inflamacion_del_higado). 
tratamiento_para(abrojo,favorece_circulacion_de_la_sangre).
tratamiento_para(acacia, garganta_estropeada). 
tratamiento_para(acacia, quemaduras). 
tratamiento_para(acacia, bronquitis). 
tratamiento_para(acacia, tos). 
tratamiento_para(acacia, dolor_de_garganta).
tratamiento_para(acanto, picadura_de_araña).
tratamiento_para(acanto, desinflamar). 
tratamiento_para(acanto, sacar_veneno). 
tratamiento_para(acanto, almorranas).
tratamiento_para(acanto, ardores_de_orina). 
tratamiento_para(acanto, heridas_por_golpe_o_caída).
tratamiento_para(acanto, dispepsia). 
tratamiento_para(aceitilla,cansancio_intelectual). 
tratamiento_para(aceitilla,depresion_nerviosa).
tratamiento_para(aceitilla,mujer_histerica).
tratamiento_para(aceitilla,mujer_con_muchos_nervios). 
tratamiento_para(aceitilla,tonicidad_nerviosa). 
tratamiento_para(aceitilla,tonicidad_cerebral).
tratamiento_para(achicoria,diuretico). 
tratamiento_para(achicoria,depurativo).
tratamiento_para(achicoria,dificil_digestion). 
tratamiento_para(achicoria,colicos_biliosos). 
tratamiento_para(achicoria,estreñimiento).
tratamiento_para(tila,calambres).
tratamiento_para(manzanilla,calambres).
tratamiento_para(ajenjo,calambres).
tratamiento_para(diente_de_león,cálculos_biliares).
tratamiento_para(aceite_de_oliva,cálculos_biliares).
tratamiento_para(retama,cálculos_biliares).
tratamiento_para(cabellos_de_elote,cálculos_renales).
tratamiento_para(pinguica,cálculos_renales).
tratamiento_para(cola_de_caballo,cálculos_renales).
tratamiento_para(ajo,callos).
tratamiento_para(cebolla,callos).
tratamiento_para(hiedra,caries).
tratamiento_para(cola_de_caballo,caries).
tratamiento_para(ortiga,caspa).
tratamiento_para(limón,caspa).
tratamiento_para(romero,caspa).
tratamiento_para(cuachalalate,cancer_de_útero).
tratamiento_para(llanten,cancer_de_útero).
tratamiento_para(siempreviva,cancer_de_útero).
tratamiento_para(mastuerzo,ciática).
tratamiento_para(higuera,ciática).
tratamiento_para(sauco,ciática).
tratamiento_para(toronjil,circulación).
tratamiento_para(sanguinaria,circulación).
tratamiento_para(salvia,circulación).
tratamiento_para(hamamelis,circulación).
tratamiento_para(cola_de_caballo,cistitis).
tratamiento_para(doradilla,cistitis).
tratamiento_para(ajo,cistitis).
tratamiento_para(cabellos_de_elote,cistitis).
tratamiento_para(menta,cólicos).
tratamiento_para(hinojo,cólicos).
tratamiento_para(manzanilla,cólicos).
tratamiento_para(toronjil,cólicos).
tratamiento_para(boldo,cólicos).
tratamiento_para(linaza,colitis).
tratamiento_para(anís,colitis).
tratamiento_para(romero,colitis).
tratamiento_para(cola_de_caballo,colitis).
tratamiento_para(árnica,contusiones).
tratamiento_para(hamamelis,contusiones).
tratamiento_para(laurel,contusiones).
tratamiento_para(briania,contusiones).
tratamiento_para(digital,corazón).
tratamiento_para(salvia,corazón).
tratamiento_para(nuez_de_kcla,corazón).
tratamiento_para(tejocote,corazón).
tratamiento_para(achicoria,depurativos_de_la_sangre).
tratamiento_para(diente_de_león,depurativos_de_la_sangre).
tratamiento_para(apio,depurativos_de_la_sangre).
tratamiento_para(sanguinaria,depurativos_de_la_sangre).
tratamiento_para(zarzaparrilla,depurativos_de_la_sangre).
tratamiento_para(berro,depurativos_de_la_sangre).
tratamiento_para(matarique,diabetes).
tratamiento_para(tronadora,diabetes).
tratamiento_para(bucalipto,diabetes).
tratamiento_para(damiana,diabetes).
tratamiento_para(capulín,diarrea_crónica).
tratamiento_para(mezquite,diarrea_crónica).
tratamiento_para(tlalchichinole,diarrea_crónica).
tratamiento_para(linaza,diarrea_por_irritación).
tratamiento_para(membrillo,diarrea_por_irritación).
tratamiento_para(arroz,diarrea_por_irritación).
tratamiento_para(cebada,diarrea_por_irritación).
tratamiento_para(guayaba,diarrea_por_inflamación).
tratamiento_para(albahaca,diarrea_por_inflamación).
tratamiento_para(granada,diarrea_por_inflamación).
tratamiento_para(manzanilla,diarrea_verdosa).
tratamiento_para(sinionillo,diarrea_verdosa).
tratamiento_para(siempreviva,diarrea_verdosa).
tratamiento_para(chaparro_amargoso,diarrea_con_sangre).
tratamiento_para(muicle,diarrea_con_sangre).
tratamiento_para(monacillo,diarrea_con_sangre).
tratamiento_para(limón,difteria).
tratamiento_para(naranja,difteria).
tratamiento_para(tamarindo,disentería).
tratamiento_para(chaparro_amargoso,disentería).
tratamiento_para(ipecacuana,disentería).
tratamiento_para(cedrón,disentería).
tratamiento_para(anís,dispepsia).
tratamiento_para(menta,dispepsia).
tratamiento_para(yerbabuena,dispepsia).
tratamiento_para(diente_de_león,dispepsia).
tratamiento_para(té_de_limón,dispepsia).
tratamiento_para(quina,dispepsia).
tratamiento_para(genciana,dispepsia).
tratamiento_para(tabequillo,dispepsia).
tratamiento_para(ruibaxbo,dispepsia).
tratamiento_para(anís_estrella,dolor).
tratamiento_para(valeriana,dolor).
tratamiento_para(manzanilla,dolor).
tratamiento_para(alcanfor,dolores_musculares).
tratamiento_para(tamarindo,empacho).
tratamiento_para(linaza,enteritis).
tratamiento_para(cedrón,enteritis).
tratamiento_para(llanten,enteritis).
tratamiento_para(valeriana,epilepsia).
tratamiento_para(hierba_del_pollo,epistaxis).
tratamiento_para(cebolla,epistaxis).
tratamiento_para(perejil,epistaxis).
tratamiento_para(sauco,erisipela).
tratamiento_para(hiedra,erisipela).
tratamiento_para(zanahoria,erisipela).
tratamiento_para(borraja,escarlatina).
tratamiento_para(sauco,escarlatina).
tratamiento_para(cebolla,escarlatina).
tratamiento_para(ajo,escorbuto).
tratamiento_para(limón,escorbuto).
tratamiento_para(berro,escorbuto).
tratamiento_para(cebolla,escorbuto).
tratamiento_para(geranio,escorbuto).
tratamiento_para(ciruela,estreñimiento).
tratamiento_para(linaza,estreñimiento).
tratamiento_para(chía,estreñimiento).
tratamiento_para(tamarindo,estreñimiento).
tratamiento_para(agar_agar,estreñimiento).
tratamiento_para(eucalipto,faringitis).
tratamiento_para(lavanda,faringitis).
tratamiento_para(anacahuite,faringitis).
tratamiento_para(apio,flatulencia).
tratamiento_para(tomillo,flatulencia).
tratamiento_para(perejil,flatulencia).
tratamiento_para(anís,flatulencia).
tratamiento_para(hinojo,flatulencia).
tratamiento_para(toronjil,flatulencia).
tratamiento_para(romero,flatulencia).
tratamiento_para(ruibarbo,flatulencia).
tratamiento_para(ruda,flatulencia).
tratamiento_para(menta,flatulencia).
tratamiento_para(malva,abscesos).
tratamiento_para(zarzaparrilla,absceso_hepático).
tratamiento_para(anís,acidez_estomacal).
tratamiento_para(perejil,acidez_estomacal).
tratamiento_para(sanguinaria,ácido_úrico).
tratamiento_para(limon,ácido_úrico).
tratamiento_para(sauco,ácido_úrico).
tratamiento_para(árnica,acné).
tratamiento_para(llanten,aftas).
tratamiento_para(fenogreco,aftas).
tratamiento_para(zarzamora,aftas).
tratamiento_para(salvia,agotamiento).
tratamiento_para(tilo,agotamiento).
tratamiento_para(valeriana,agotamiento).
tratamiento_para(yerbabuena,agruras).
tratamiento_para(manzanilla,agruras).
tratamiento_para(jugo_de_limón,agruras).
tratamiento_para(jugo_de_toronja,agruras).
tratamiento_para(pingüica,albuminaria).
tratamiento_para(quinoa_roja,albuminaria).
tratamiento_para(encino_rojo,albuminaria).
tratamiento_para(pimiento,alcoholismo).
tratamiento_para(salvia,almorranas).
tratamiento_para(huramelis,almorranas).
tratamiento_para(sanguinaria,almorranas).
tratamiento_para(cola_de_caballo,almorranas).
tratamiento_para(arnica,almorranas).
tratamiento_para(sauco,almorranas).
tratamiento_para(ajenjo,anemia).
tratamiento_para(germen_de_trigo,anemia).
tratamiento_para(quira,anemia).
tratamiento_para(canela,anemia).
tratamiento_para(alholva,anemia).
tratamiento_para(eucalipto,anginas).
tratamiento_para(cebada,anginas).
tratamiento_para(salvia,anginas).
tratamiento_para(tabachin,anginas).
tratamiento_para(borraja,anginas).
tratamiento_para(ajenjo,anorexia).
tratamiento_para(gerciana,anorexia).
tratamiento_para(yerbabuena,anorexia).
tratamiento_para(limón,arterosclerosis).
tratamiento_para(genciana,arterosclerosis).
tratamiento_para(cardo,arterosclerosis).
tratamiento_para(zarzaparrilla,arterosclerosis).
tratamiento_para(arnica,arterosclerosis).
tratamiento_para(chicalote,arterosclerosis).
tratamiento_para(alcanfor,arterosclerosis).
tratamiento_para(toronja,arterosclerosis).
tratamiento_para(limón,artritis).
tratamiento_para(genciana,artritis).
tratamiento_para(cardo,artritis).
tratamiento_para(zarzaparrilla,artritis).
tratamiento_para(arnica,artritis).
tratamiento_para(chicalote,artritis).
tratamiento_para(alcanfor,artritis).
tratamiento_para(toronja,artritis).
tratamiento_para(eucalipto,asma).
tratamiento_para(merrubio,asma).
tratamiento_para(toloache,asma).
tratamiento_para(oregano,asma).
tratamiento_para(salvia,asma).
tratamiento_para(lupulo,atonia_estomacal).
tratamiento_para(eucalipto,atonia_estomacal).
tratamiento_para(cuasia,atonia_estomacal).
tratamiento_para(uva,bazo).
tratamiento_para(cerezo,bazo).
tratamiento_para(malva,inflamación_de_la_boca).
tratamiento_para(rosal,inflamación_de_la_boca).
tratamiento_para(limón,inflamación_de_la_boca).
tratamiento_para(salvia,inflamación_de_la_boca).
tratamiento_para(rosal,estomatitis).
tratamiento_para(encina,estomatitis).
tratamiento_para(salvia,estomatitis).
tratamiento_para(zarzamora,estomatitis).
tratamiento_para(eucalipto,bronquitis).
tratamiento_para(borraga,bronquitis).
tratamiento_para(anacahuite,bronquitis).
tratamiento_para(gordolobo,bronquitis).
tratamiento_para(tilo,bronquitis).
tratamiento_para(benjui,bronquitis).
tratamiento_para(marrubio,bronquitis).
tratamiento_para(rabano,bronquitis).
tratamiento_para(gordolobo,bronconeumonia).
tratamiento_para(eucalipto,bronconeumonia).
tratamiento_para(ipecacuana,bronconeumonia).
tratamiento_para(mostaza,bronconeumonia).
tratamiento_para(ortiga,caida_del_cabello).
tratamiento_para(espinosilla,caida_del_cabello).
tratamiento_para(marrubio,caida_del_cabello).
tratamiento_para(romero,caida_del_cabello).
tratamiento_para(anís,calambres).

%Forma empleo
modo_de_empleo(abrojo,usar_como_agua_de_uso).
modo_de_empleo(acacia, chupar_savia_seca_o_hacer_polvos).
modo_de_empleo(acanto,aplicar_hojas_sobre_la_zona_afectada).
modo_de_empleo(acanto,hacer_té_con_las_hojas).
modo_de_empleo(aceitilla,hacer_te_con_la_planta).
modo_de_empleo(achicora,hacer_te_con_las_hojas_secas).

produce(digital,tonico_cardiaco).
produce(opio,morfina).
produce(ipeca,emetina).
produce(nuez vomica,estrienica).
produce(eleboro_blanco,veratrina).
produce(colchico,colquicina).
produce(belladona,atropina).
produce(quina,quina).
produce(cacao,teobromina).
produce(retama,esparteina).
produce(coca,cocaina).
produce(peyote,mescalina).
produce(efedra,efedrina).
produce(barrasco,hormonas).
produce(nenufar_amarillo,lutenurina).
produce(artemisa,tauremisina).
produce(semilla_de_yute,olitorisida).
produce(toloache,acido_lisergico).
produce(eucalipto,eucaliptol).
produce(rosal,vitamina_c).

%Reglas
significa(afrodisiaca,exita_el_apetito_sexual).
significa(analgesica,quita_o_modera_el_dolor).
significa(anestesica,insensibiliza_el_cuerpo).
significa(antidiarreica,controla_diarreas).
significa(antiespasmodica,controla_espasmos_nerviosos).
significa(antiflogistica,ayuda_con_inflamaciones).
significa(antipiretica,quita_la_fiebre).
significa(antiseptica,mata_los_tejidos).
significa(aperitiva,deseo_de_comer).
significa(astringente,contrae_los_tejidos).
significa(carminativa,evita_formacion_de_gases).
significa(colagoga,ayuda_a_expulsar_la_bilis).
significa(depurativa,limpia_y_purifica_la_sangre).
significa(diaforetica,provoca_sudoracion_como_cochino).
significa(digestiva,favorece_a_la_digestion).
significa(diuretica,provoca_la_orina).
significa(emetica,provoca_nauseas_y_vomitos).
significa(emenagoga,activa_la_menstruacion).
significa(estupefaciente,ayuda_a_tranquilizar).
significa(hemostatica,detiene_las_hemorragias).
significa(hepatica,ayuda_al_higado).
significa(laxante,purga_sin_provocar_diarrea).
significa(pectoral,ayuda_al_pecho).
significa(sedante,calma_dolores_intestinales).
significa(tonica,fortalece_el_organismo).
significa(toxica,es_venenosa).
significa(vermifuga,expulsa_gusanos_intestinales).
significa(vulneraria,cura_llagas_y_heridas).


padecimiento(anemia).
padecimiento(debilidad).
padecimiento(gripe).
padecimiento(gases).
padecimiento(mala_digestion).
padecimiento(colicos).
padecimiento(nauseas).
padecimiento(flatulencias).
padecimiento(mala_digestion).
padecimiento(nubes_en_los_ojos).
++
se_usa_en(canela,tónico).
se_usa_en(canela,té).
se_usa_en(cedron,cocimiento).
se_usa_en(cedron,agua_de_uso).
se_usa_en(cardo_santo,macerado).
se_usa_en(cardo_santo,lavados).
se_usa_en(cardo_santo,jugo_).
se_usa_en(cardo_santo,cocimiento).

tratamiento_para(malva,abscesos).
tratamiento_para(zarzaparrilla,absceso_hepático).
tratamiento_para(anís,acidez_estomacal).
tratamiento_para(perejil,acidez_estomacal).
tratamiento_para(sanguinaria,ácido_úrico).
tratamiento_para(limon,ácido_úrico).
tratamiento_para(sauco,ácido_úrico).
tratamiento_para(árnica,acné).
tratamiento_para(llanten,aftas).
tratamiento_para(fenogreco,aftas).
tratamiento_para(zarzamora,aftas).
tratamiento_para(salvia,agotamiento).
tratamiento_para(tilo,agotamiento).
tratamiento_para(valeriana,agotamiento).
tratamiento_para(yerbabuena,agruras).
tratamiento_para(manzanilla,agruras).
tratamiento_para(jugo_de_limón,agruras).
tratamiento_para(jugo_de_toronja,agruras).
tratamiento_para(pingüica,albuminaria).
tratamiento_para(quinoa_roja,albuminaria).
tratamiento_para(encino_rojo,albuminaria).
tratamiento_para(pimiento,alcoholismo).
tratamiento_para(salvia,almorranas).
tratamiento_para(huramelis,almorranas).
tratamiento_para(sanguinaria,almorranas).
tratamiento_para(cola_de_caballo,almorranas).
tratamiento_para(arnica,almorranas).
tratamiento_para(sauco,almorranas).
tratamiento_para(ajenjo,anemia).
tratamiento_para(germen_de_trigo,anemia).
tratamiento_para(quira,anemia).
tratamiento_para(canela,anemia).
tratamiento_para(alholva,anemia).
tratamiento_para(eucalipto,anginas).
tratamiento_para(cebada,anginas).
tratamiento_para(salvia,anginas).
tratamiento_para(tabachin,anginas).
tratamiento_para(borraja,anginas).
tratamiento_para(ajenjo,anorexia).
tratamiento_para(gerciana,anorexia).
tratamiento_para(yerbabuena,anorexia).
tratamiento_para(limón,arterosclerosis).
tratamiento_para(genciana,arterosclerosis).
tratamiento_para(cardo,arterosclerosis).
tratamiento_para(zarzaparrilla,arterosclerosis).
tratamiento_para(arnica,arterosclerosis).
tratamiento_para(chicalote,arterosclerosis).
tratamiento_para(alcanfor,arterosclerosis).
tratamiento_para(toronja,arterosclerosis).
tratamiento_para(limón,artritis).
tratamiento_para(genciana,artritis).
tratamiento_para(cardo,artritis).
tratamiento_para(zarzaparrilla,artritis).
tratamiento_para(arnica,artritis).
tratamiento_para(chicalote,artritis).
tratamiento_para(alcanfor,artritis).
tratamiento_para(toronja,artritis).
tratamiento_para(eucalipto,asma).
tratamiento_para(merrubio,asma).
tratamiento_para(toloache,asma).
tratamiento_para(oregano,asma).
tratamiento_para(salvia,asma).
tratamiento_para(lupulo,atonia_estomacal).
tratamiento_para(eucalipto,atonia_estomacal).
tratamiento_para(cuasia,atonia_estomacal).
tratamiento_para(uva,bazo).
tratamiento_para(cerezo,bazo).
tratamiento_para(malva,inflamación_de_la_boca).
tratamiento_para(rosal,inflamación_de_la_boca).
tratamiento_para(limón,inflamación_de_la_boca).
tratamiento_para(salvia,inflamación_de_la_boca).
tratamiento_para(rosal,estomatitis).
tratamiento_para(encina,estomatitis).
tratamiento_para(salvia,estomatitis).
tratamiento_para(zarzamora,estomatitis).
tratamiento_para(eucalipto,bronquitis).
tratamiento_para(borraga,bronquitis).
tratamiento_para(anacahuite,bronquitis).
tratamiento_para(gordolobo,bronquitis).
tratamiento_para(tilo,bronquitis).
tratamiento_para(benjui,bronquitis).
tratamiento_para(marrubio,bronquitis).
tratamiento_para(rabano,bronquitis).
tratamiento_para(gordolobo,bronconeumonia).
tratamiento_para(eucalipto,bronconeumonia).
tratamiento_para(ipecacuana,bronconeumonia).
tratamiento_para(mostaza,bronconeumonia).
tratamiento_para(ortiga,caida_del_cabello).
tratamiento_para(espinosilla,caida_del_cabello).
tratamiento_para(marrubio,caida_del_cabello).
tratamiento_para(romero,caida_del_cabello).
tratamiento_para(anís,calambres).

%PLANTAS DE LA LISTA ASIGNADAS 
planta(diente_de_leon).
planta(digitaria).
planta(doradilla).

se_cataloga(depurativa).
se_cataloga(aperitivo).
se_cataloga(laxante).
se_cataloga(diuretico).
se_cataloga(colagoga).
se_cataloga(refrescante).

tratamiento_para(limpiador_de_sangre).
tratamiento_para(purifica_higado).
tratamiento_para(purifica_riñones).
tratamiento_para(anemia).
tratamiento_para(males_cardiacos).
tratamiento_para(miocarditis).
tratamiento_para(astenia).
tratamiento_para(asistolia).
tratamiento_para(epilepsia).
tratamiento_para(calculos_biliares).
tratamiento_para(afeccion_vejiga).
